export { default as FrontView } from './front_view.png'
export { default as ExplodedView } from './exploded_view.png'
export { default as IsometricProjection } from './isometric_projection.png'
export { default as BottomView } from './bottom_view.jpeg'
export { default as Connection } from './connection.jpeg'
