/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDataSheetRouteImport } from './routes/_app/data-sheet'
import { Route as AppProductCatalogRouteImport } from './routes/_app/product-catalog'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSheetRoute = AppDataSheetRouteImport.update({
  id: '/data-sheet',
  path: '/data-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppProductCatalogRoute = AppProductCatalogRouteImport.update({
  id: '/product-catalog',
  path: '/product-catalog',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/data-sheet': typeof AppDataSheetRoute
  '/product-catalog': typeof AppProductCatalogRoute
}
export interface FileRoutesByTo {
  '/data-sheet': typeof AppDataSheetRoute
  '/product-catalog': typeof AppProductCatalogRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/data-sheet': typeof AppDataSheetRoute
  '/_app/product-catalog': typeof AppProductCatalogRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-sheet' | '/product-catalog'
  fileRoutesByTo: FileRoutesByTo
  to: '/data-sheet' | '/product-catalog' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/data-sheet'
    | '/_app/product-catalog'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-sheet': {
      id: '/_app/data-sheet'
      path: '/data-sheet'
      fullPath: '/data-sheet'
      preLoaderRoute: typeof AppDataSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product-catalog': {
      id: '/_app/product-catalog'
      path: '/product-catalog'
      fullPath: '/product-catalog'
      preLoaderRoute: typeof AppProductCatalogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDataSheetRoute: typeof AppDataSheetRoute
  AppProductCatalogRoute: typeof AppProductCatalogRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDataSheetRoute: AppDataSheetRoute,
  AppProductCatalogRoute: AppProductCatalogRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
